[package]
name = "vp-kuljetus-vehicle-data-receiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitconv = "0.1.4"
nom-teltonika = { version = "0.1.4", features = ["serde", "tokio"] }
tokio = { version = "1.33.0", features = ["full", "tracing"] }