[package]
name = "vp-kuljetus-vehicle-data-receiver"
edition = "2021"
version = "0.7.0"
readme = "README.md"

[dependencies]
base64 = "0.21.0"
env_logger = "0.10.0"
futures = "0.3.25"
httpclient = "0.20.2"
log = "0.4.20"
serde_derive = "1.0.197"
serde_json = "1.0.81"

[dependencies.chrono]
version = "0.4.33"
features = ["serde"]
default-features = false

[dependencies.nom-teltonika]
version = "0.1.4"
features = ["serde", "tokio"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]
default-features = false

[dependencies.tokio]
version = "1.33.0"
features = ["full", "tracing"]

[dependencies.vehicle-management-service]
path = "./vehicle-management-service"

[dev-dependencies]
rand = "0.8.5"

[dev-dependencies.tokio]
version = "1.18.2"
features = ["full"]
