/*
 * Vehicle Management Services (vehicle-data-receiver)
 *
 * Vehicle Management Services (vehicle-data-receiver)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`receive_telematic_data`]
#[derive(Clone, Debug)]
pub struct ReceiveTelematicDataParams {
    /// Truck or towable vehicle identification number
    pub vin: String,
    /// Payload
    pub telematic_data: models::TelematicData
}


/// struct for typed errors of method [`receive_telematic_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReceiveTelematicDataError {
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}


/// Receives telematic data entry
pub fn receive_telematic_data(configuration: &configuration::Configuration, params: ReceiveTelematicDataParams) -> Result<(), Error<ReceiveTelematicDataError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let vin = params.vin;
    let telematic_data = params.telematic_data;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/vehicle-management/v1/telematics/{vin}", local_var_configuration.base_path, vin=crate::apis::urlencode(vin));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_apikey) = local_var_configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
    };
    local_var_req_builder = local_var_req_builder.json(&telematic_data);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req)?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text()?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        Ok(())
    } else {
        let local_var_entity: Option<ReceiveTelematicDataError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

