/*
 * Vehicle Management Services (vehicle-data-receiver)
 *
 * Vehicle Management Services (vehicle-data-receiver)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`create_temperature_reading`]
#[derive(Clone, Debug)]
pub struct CreateTemperatureReadingParams {
    /// Payload
    pub truck_or_towable_temperature_reading: models::TruckOrTowableTemperatureReading
}


/// struct for typed errors of method [`create_temperature_reading`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTemperatureReadingError {
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}


/// Create temperature reading
pub async fn create_temperature_reading(configuration: &configuration::Configuration, params: CreateTemperatureReadingParams) -> Result<(), Error<CreateTemperatureReadingError>> {

    let uri_str = format!("{}/v1/temperatureReadings", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("X-DataReceiver-API-Key", value);
    };
    req_builder = req_builder.json(&params.truck_or_towable_temperature_reading);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTemperatureReadingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

