/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_trackable_by_imei`]
#[derive(Clone, Debug)]
pub struct GetTrackableByImeiParams {
    /// IMEI of the trackable
    pub imei: String
}


/// struct for typed errors of method [`get_trackable_by_imei`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTrackableByImeiError {
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}


/// Finds a trackable e.g. a truck or a towable by its IMEI.
pub async fn get_trackable_by_imei(configuration: &configuration::Configuration, params: GetTrackableByImeiParams) -> Result<models::Trackable, Error<GetTrackableByImeiError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let imei = params.imei;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v1/trackables/{imei}", local_var_configuration.base_path, imei=crate::apis::urlencode(imei));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_apikey) = local_var_configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.header("X-DataReceiver-API-Key", local_var_value);
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetTrackableByImeiError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

