pub mod ping;
pub mod list_trucks;
pub mod create_truck;
pub mod find_truck;
pub mod update_truck;
pub mod delete_truck;
pub mod list_towables;
pub mod create_towable;
pub mod find_towable;
pub mod update_towable;
pub mod delete_towable;
pub mod receive_telematic_data;
pub mod list_vehicles;
pub mod create_vehicle;
pub mod find_vehicle;
pub mod delete_vehicle;
pub use ping::PingRequest;
pub use list_trucks::ListTrucksRequest;
pub use create_truck::CreateTruckRequest;
pub use find_truck::FindTruckRequest;
pub use update_truck::{UpdateTruckRequest, UpdateTruckRequired};
pub use delete_truck::DeleteTruckRequest;
pub use list_towables::ListTowablesRequest;
pub use create_towable::CreateTowableRequest;
pub use find_towable::FindTowableRequest;
pub use update_towable::{UpdateTowableRequest, UpdateTowableRequired};
pub use delete_towable::DeleteTowableRequest;
pub use receive_telematic_data::{
    ReceiveTelematicDataRequest, ReceiveTelematicDataRequired,
};
pub use list_vehicles::ListVehiclesRequest;
pub use create_vehicle::CreateVehicleRequest;
pub use find_vehicle::FindVehicleRequest;
pub use delete_vehicle::DeleteVehicleRequest;