/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemperatureReading : Represents a single temperature reading being received from a thermometer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemperatureReading {
    /// unique ID of the device the sensor is connected to. ID is an IMEI when value is received from truck or towable and MAC address when received from terminal. 
    #[serde(rename = "deviceIdentifier")]
    pub device_identifier: String,
    /// Unique mac address of the thermometer that is sending this temperature reading
    #[serde(rename = "macAddress")]
    pub mac_address: String,
    /// The temperature value in Celsius
    #[serde(rename = "value")]
    pub value: f32,
    /// Timestamp for when the temperature was read. Unix timestamp in milliseconds.
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
}

impl TemperatureReading {
    /// Represents a single temperature reading being received from a thermometer
    pub fn new(device_identifier: String, mac_address: String, value: f32, timestamp: i64) -> TemperatureReading {
        TemperatureReading {
            device_identifier,
            mac_address,
            value,
            timestamp,
        }
    }
}

