/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Trackable : Represents a trackable entity e.g. truck or towable
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Trackable {
    /// Unique identifier for the trackable entity e.g. truck or towable
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// IMEI of the trackable entity
    #[serde(rename = "imei")]
    pub imei: String,
    #[serde(rename = "trackableType")]
    pub trackable_type: models::TrackableType,
}

impl Trackable {
    /// Represents a trackable entity e.g. truck or towable
    pub fn new(id: uuid::Uuid, imei: String, trackable_type: models::TrackableType) -> Trackable {
        Trackable {
            id,
            imei,
            trackable_type,
        }
    }
}

