/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrackableType {
    #[serde(rename = "TRUCK")]
    Truck,
    #[serde(rename = "TOWABLE")]
    Towable,
}

impl std::fmt::Display for TrackableType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Truck => write!(f, "TRUCK"),
            Self::Towable => write!(f, "TOWABLE"),
        }
    }
}

impl Default for TrackableType {
    fn default() -> TrackableType {
        Self::Truck
    }
}
