/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TruckOdometerReading {
    /// Truck odometer ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Timestamp for truck odometer.
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    /// Odometer reading in meters. See [Teltonika FMC650 Data Sending Parameters ID - Tachograph Data Elements](https://wiki.teltonika-gps.com/view/FMC650_Teltonika_Data_Sending_Parameters_ID#Tachograph_data_elements)
    #[serde(rename = "odometerReading")]
    pub odometer_reading: i32,
}

impl TruckOdometerReading {
    pub fn new(timestamp: i64, odometer_reading: i32) -> TruckOdometerReading {
        TruckOdometerReading {
            id: None,
            timestamp,
            odometer_reading,
        }
    }
}
