/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TruckDriveStateEnum {
    #[serde(rename = "REST")]
    Rest,
    #[serde(rename = "DRIVER_AVAILABLE")]
    DriverAvailable,
    #[serde(rename = "WORK")]
    Work,
    #[serde(rename = "DRIVE")]
    Drive,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "NOT_AVAILABLE")]
    NotAvailable,
}

impl std::fmt::Display for TruckDriveStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Rest => write!(f, "REST"),
            Self::DriverAvailable => write!(f, "DRIVER_AVAILABLE"),
            Self::Work => write!(f, "WORK"),
            Self::Drive => write!(f, "DRIVE"),
            Self::Error => write!(f, "ERROR"),
            Self::NotAvailable => write!(f, "NOT_AVAILABLE"),
        }
    }
}

impl Default for TruckDriveStateEnum {
    fn default() -> TruckDriveStateEnum {
        Self::Rest
    }
}
