/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TruckSortByField {
    #[serde(rename = "NAME")]
    Name,
    #[serde(rename = "PLATE_NUMBER")]
    PlateNumber,
}

impl std::fmt::Display for TruckSortByField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Name => write!(f, "NAME"),
            Self::PlateNumber => write!(f, "PLATE_NUMBER"),
        }
    }
}

impl Default for TruckSortByField {
    fn default() -> TruckSortByField {
        Self::Name
    }
}
