/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TruckSpeed {
    /// Truck speed ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Timestamp for truck speed. Unix timestamp in milliseconds.
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "speed")]
    pub speed: f32,
}

impl TruckSpeed {
    pub fn new(timestamp: i64, speed: f32) -> TruckSpeed {
        TruckSpeed {
            id: None,
            timestamp,
            speed,
        }
    }
}
