/*
 * VP-Kuljetus Vehicle Management Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Vehicle : Represent single vehicle
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vehicle {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Truck that towing the vehicle
    #[serde(rename = "truckId")]
    pub truck_id: uuid::Uuid,
    /// List of attached towables to vehicle. Order of towables should reflect the order of towables in the vehicle where first towable is the closest to the truck.
    #[serde(rename = "towableIds")]
    pub towable_ids: Vec<uuid::Uuid>,
    #[serde(rename = "creatorId", skip_serializing_if = "Option::is_none")]
    pub creator_id: Option<uuid::Uuid>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "lastModifierId", skip_serializing_if = "Option::is_none")]
    pub last_modifier_id: Option<uuid::Uuid>,
    #[serde(rename = "modifiedAt", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    /// Setting the archivedAt time marks the vehicle as archived. Vehicles marked as archived will not appear in list requests unless archived filter is set to true. Archived vehicle cannot be updated, unless archivedAt is first set to null.
    #[serde(rename = "archivedAt", skip_serializing_if = "Option::is_none")]
    pub archived_at: Option<String>,
}

impl Vehicle {
    /// Represent single vehicle
    pub fn new(truck_id: uuid::Uuid, towable_ids: Vec<uuid::Uuid>) -> Vehicle {
        Vehicle {
            id: None,
            truck_id,
            towable_ids,
            creator_id: None,
            created_at: None,
            last_modifier_id: None,
            modified_at: None,
            archived_at: None,
        }
    }
}
